gpu: true
data_dir: ""
load: false
load_dir: "./logdir/[env]/PSDRL-[name]/[seed]/checkpoints/[timestep]/"
visual: True

logging:
  data_manager: wandb
  save_model: False
  save_freq: 1.0e5 
  n_rollouts: 2
  rollout_freq: 1.0e4  
  n_diversity: 5
  diveristy_freq: 1.0e4


algorithm:
  name: PSDRL
  bayesian: lpbnn
  update_freq: 1e3
  warmup_length: 1e5
  warmup_freq: 250
  policy_noise_start: 0.001
  policy_noise_end: 0.001

experiment:
  suite: atari
  env: Pong
  test: true
  steps: 1e6
  time_limit: 27000
  test_freq: 1e4
  name: ""
  seed: None

replay:
  capacity: 1e5
  batch_size: 128
  sequence_length: 250

transition:
  ensemble_size: 4
  vae_embedding_size: 32
  init_strategy: pmnormal
  elbow_weight: 1
  training_iterations: 3
  hidden_dim: 1536
  gru_dim: 756
  learning_rate: 1e-4
  bnn_lr: 1e-2
  window_length: 4
  bnn_layer_count: 0

value:
  training_iterations: 3
  hidden_dim: 1536
  learning_rate: 1e-4
  target_update_freq: 4
  discount: 0.99

terminal:
  training_iterations: 3
  hidden_dim: 1536
  learning_rate: 1e-4

representation:
  training_iterations: 3
  learning_rate: 1e-4
  embed_dim: 1536

